[package]
name = "yew-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
js-sys = "0.3"
arraymap = "0.1"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
gloo-timers = "0.2.4"
gloo-console = "0.2.3"
