name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ./target
          ~/.cargo
        key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: beta
        override: true
        target: wasm32-unknown-unknown

    - name: Install cargo dependencies
      run: cargo install trunk wasm-bindgen-cli

    - name: Build
      run: trunk build

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: |
          dist

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
