name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        rustup toolchain install beta
        rustup override set beta
        rustup target add wasm32-unknown-unknown
        cargo install trunk wasm-bindgen-cli
    - name: Build
      run: trunk build
