name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ./target
          ~/.cargo
        key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
          
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: beta
        override: true
        target: wasm32-unknown-unknown

    - name: Install cargo dependencies
      run: cargo install trunk wasm-bindgen-cli

    - name: Build
      run: trunk build
